# Çoklu Doğrusal Regresyon Modeli

### Model

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df= pd.read_csv("Advertising.csv")
df=df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [5]:
df.isnull().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [9]:
X = df.drop("sales" , axis=1)
y = df[["sales"]]

In [10]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [11]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

#### Statsmodels ile model kurmak

In [12]:
import statsmodels.api as sm

In [13]:
lm = sm.OLS(y,X)

In [14]:
model = lm.fit()

In [15]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Thu, 27 Apr 2023   Prob (F-statistic):                   2.43e-171
Time:                        16:11:18   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

#### scikit learn ile model kurmak

In [17]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [19]:
model = lm.fit(X,y)

In [20]:
model.intercept_ #b0

array([2.93888937])

In [22]:
model.coef_ #b1,b2,b3 katsayıları

array([[ 0.04576465,  0.18853002, -0.00103749]])

### Tahmin

__sales = 2.94+TV * 0.04+radio * 0.19-newapaper * 0.001__


30 birim TV, 10 birim radio , 40 birim newspaper

In [28]:
2.94 + 30 * 0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [24]:
yeni_veri = [[30], [10], [40]]

In [25]:
yeni_veri = pd.DataFrame(yeni_veri).T

In [26]:
yeni_veri

0   1   2
0  30  10  40

In [27]:
model.predict(yeni_veri)

array([[6.15562918]])

In [29]:
from sklearn.metrics import mean_squared_error

In [30]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [31]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [33]:
MSE = mean_squared_error(y,model.predict(X))
MSE

2.784126314510936

In [34]:
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

### Model Tuning (Model Doğrulama)

In [36]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [37]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [38]:
#sınama seti

In [39]:
from sklearn.model_selection import train_test_split

In [49]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.20 , random_state=99)

In [42]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [50]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [44]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [52]:
lm = LinearRegression()
model = lm.fit(X_train , y_train)
model

LinearRegression()

In [55]:
#eğitim hatası
np.sqrt(mean_squared_error(y_train , model.predict(X_train)))

1.7236824822650751

In [56]:
#test hatası
np.sqrt(mean_squared_error(y_test , model.predict(X_test)))

1.4312783138301641

#### k katlı cv

seçilen yüzde 20 ve yüzde 80lik kısımlar hangi parçalardan seçildi. bu fark yaratır. o yüzden k katlı cv kullanmak çok daha mantıklıdır.

In [57]:
from sklearn.model_selection import cross_val_score

In [59]:
cross_val_score(model,X_train , y_train , cv=10, scoring = "neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [60]:
# cv mse 
np.mean(-cross_val_score(model,X_train , y_train , cv=10, scoring = "neg_mean_squared_error"))

3.317028974234127

In [61]:
# cv rmse 
np.sqrt(np.mean(-cross_val_score(model,X_train , y_train , cv=10, scoring = "neg_mean_squared_error")))

1.821271252239525